### ISSUE TITLE
Support W3C trace context

### ISSUE THREAD

**Issue by breedx-nr** [kamon-io/kanela#103]
It's great that Kanela supports the zipkin B3 headers, but it would be fantastic if it also supported the newer and interoperable W3C trace context https://www.w3.org/TR/trace-context/

**Comment by dpsoft** [comment]
Hi @breedx-nr, thanks for proposing this @ivantopo had created a kamon codec a while ago: https://github.com/kamon-io/kamon-tracecontext-codec/blob/master/src/main/scala/kamon/ trace / W3CTraceContextCodec.scala we should incorporate it (with some changes in the middle) to the current version that is 2.0.

**Comment by breedx-nr** [comment]
Hi @dpsoft.  Thanks for the update!  It's good to hear that we can look forward to this in a future release.

**Comment by dpsoft** [comment]
this feature is related to `kamon-core`

**Comment by ivantopo** [comment]
We are keeping track of that feature here: https://github.com/kamon-io/Kamon/issues/802
