### ISSUE TITLE
Mdc context propagation doen't not work with kanela-agent 1.0.10

### ISSUE THREAD

**Issue by yarosman** [kamon-io/kanela#129]
After migration to `kanela-agent` from `1.0.9` to `1.0.10` mdc context stopped propagate in logs. 
With 1.0.9 everything works fine. Kamon version didn't change.

**Comment by yarosman** [comment]
it's not agent error

**Comment by dpsoft** [comment]
@yarosman can you try with `Kanela 1.0.11`?

**Comment by yarosman** [comment]
> @yarosman can you try with `Kanela 1.0.11`?

I'll try next week, I am waiting for `kamon 2.2.0` with new-old version of future instrumentation

**Comment by yarosman** [comment]
> @yarosman can you try with `Kanela 1.0.11`?

Hello. At first point looks that everything works fine with kanela-agent 1.0.11 аnd kamon 2.2.0
