### ISSUE TITLE
Kanela 1.0.17 tag and release notes

### ISSUE THREAD

**Issue by Philippus** [kamon-io/kanela#149]
The latest version of kanela agent is 1.0.17, it is also mentioned here: https://github.com/kamon-io/Kamon/releases/tag/v2.6.0. But there is not tag in GitHub and there are no release notes.

**Comment by ivantopo** [comment]
Hey @Philippus, thanks for mentioning this! I totally forgot this part of the release ritual (usually I only do the Kamon releases :smile:)

I pushed the tag and added release notes here: https://github.com/kamon-io/kanela/releases/tag/v1.0.17
