### ISSUE TITLE
JVM 20/21 LTS support

### ISSUE THREAD

**Issue by nvollmar** [kamon-io/kanela#150]
Kanela is quite behind in byte buddy versions:
1.12.18+ would have ASM 9.4 with support for JVM 20
1.14.3+ would have ASM 9.5 with support for JVM 21.

**Comment by ivantopo** [comment]
Hey @nvollmar, thanks for the heads up. Every time there is a new JVM @dpsoft makes his magic and a new Kanela version comes out so hopefully this will push him :joy:

**Comment by dpsoft** [comment]
Hi guys, I think that over the weekend I will be able to do a new release of Kanela

**Comment by danischroeter** [comment]
Hi @dpsoft 
We would like to move forward to jdk 20 and are blocked on this. Any chance you could release kanela with the latest bytebuddy this week? Help needed?

**Comment by dpsoft** [comment]
@danischroeter @danischroeter https://github.com/kamon-io/kanela/releases/tag/v1.0.18
