### ISSUE TITLE
Update build

### ISSUE THREAD

**Issue by nvollmar** [kamon-io/kanela#152]
The currently used version of Gradle does not work with JDK 20+. But upgrading is not trivial as the scala test runner plugin is unmaintained and incompatible with newer versions.

The best option forward would probably be switching to sbt, or are there any important reasons why Gradle was used instead?

**Comment by dpsoft** [comment]
The reason Kanela uses Gradle is that it is primarily a Java project, not a Scala project. This choice is motivated by the fact that Gradle is well-suited for Java projects. Additionally, we are using the latest version of Gradle, which is currently 8.4 (RC). This version of Gradle supports Java 21, and in our latest release, we ensure test using this Java version.

https://github.com/kamon-io/kanela/blob/master/.github/workflows/ci.yml#L11

**Comment by nvollmar** [comment]
Ah, missed that
