### ISSUE TITLE
Can't see exception causes in the logs

### ISSUE THREAD

**Issue by ivantopo** [kamon-io/kanela#99]
While I was investigating #98 I noticed that "causes" of exceptions are not being displayed in the logs. For example, see the message we got from this error in the logs: "java.lang.RuntimeException: The class file could not be written"

![image](https://user-images.githubusercontent.com/1302854/68537307-bd3faf80-0361-11ea-9f8f-4b5bcfd79b6d.png)

I was suspicious that there was something else behind that and only after running with a debugger to investigate further I could see that the actual issue was a problem with not finding a class file:

![image](https://user-images.githubusercontent.com/1302854/68537301-984b3c80-0361-11ea-85ad-cc6c524e80b7.png)

Ideally it would be nice to see the whole stack trace for the main exception and all the "caused by" as we see in some other places.

**Comment by dpsoft** [comment]
fixed with https://github.com/kamon-io/kanela/commit/a22440f76424ba69c4f16afd4ce36c1abf699aee
